name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Build
      run: msbuild /p:configuration=Release -restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal 
    - name: Benchmark
      run: cd Linq2d.Benchmarks; sudo dotnet run -c Release --no-build --filter "*";
