name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal 
    - name: Lookaround
      run: ls 
    - name: Lookaround 1
      run: ls ./Linq2d.Benchmarks
    - name: Lookaround 2
      run: ls ./Linq2d.Benchmarks/bin
    - name: Lookaround 3
      run: ls ./Linq2d.Benchmarks/bin/Release
    - name: Lookaround 4
      run: ls ./Linq2d.Benchmarks/bin/Release/netcoreapp3.1
    - name: Benchmark
      run: dotnet run ./Linq2d.Benchmarks/bin/Release/netcoreapp3.1/Linq2d.Benchmarks.dll --runtimes netcoreapp3.1 --filter *
